### ISSUE TITLE
1.1

### ISSUE THREAD

**Issue by KuLou99** [haxi0/TrollApps#15]
15.2系统打来app崩溃，无法正常使用

**Comment by haxi0** [comment]
please write in English

**Comment by KuLou99** [comment]
> please write in English

15.2 The system crashed when it opened the app and could not be used normally. The app was stuck and crashed.

**Comment by MoeAlAssi** [comment]
Its opening magnifier

**Comment by haxi0** [comment]
trollstore 1.4 fixed that
