### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by ConnorDoesDev** [haxi0/TrollApps#18]
System Details:
15.2.1
A14 (iPhone 12 mini)

TrollApps instantly crashes on startup.

**Comment by Landen1345** [comment]
Same for me in 15.1 IPhone 8 A11

**Comment by FrankenSpine310** [comment]
Same for me. 8 plus 15.1

**Comment by pryid** [comment]
iphone se (1st gen) ios 15.3 same!

**Comment by LegitSoulja** [comment]
It was working but now just crashes, i believe due to url resolving issues giving exceptions when loaded.

**Comment by Landen1345** [comment]
he updated the read me with what causes the crashing, rhe website is blocked

**Comment by haxi0** [comment]
website is down, 1.2 will fix that
