### ISSUE TITLE
Adding sources causes the app to crash

### ISSUE THREAD

**Issue by swaggyP36000** [haxi0/TrollApps#21]
I've tried to add the Quantum source and RandomSource. They're both links to .json files for apps but they cause TrollApps to crash. After adding, every time I click on the Sources & Apps tab the app crashes until I go to the Settings tab and Delete All Sources

These work fine on ESign. Are there different sources that work better for TrollApps?

**Comment by haxi0** [comment]
they are not made for trollapps, trollapps has a different json
