### ISSUE TITLE
iPhone Xs plus 14.7 not working correctly 

### ISSUE THREAD

**Issue by AppleiGod** [haxi0/TrollApps#23]
I don’t know what but whenever I try to get any app it just opens up this weird camera app I’ve never seen before if I have the app on there it will open the app but any other ones I try to get just opens up a weird camera app I made a video

https://user-images.githubusercontent.com/50977642/203710203-740c47e5-f99f-4ee7-8de5-4fa7eb6e2c46.MP4

**Comment by haxi0** [comment]
check my twitter for a solution
